import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App by Symbat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
