import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import ClientProvider from "@/components/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App by Symbat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <NavBar />
          <main> {children}</main>
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
